version: '3.8'

services:
  web:
    build:
      context: ./static-web-server # Chemin vers le dossier contenant votre Dockerfile
    ports:
      - "8080:80" # Mappe le port 80 du conteneur au port 8080 de votre machine
    container_name: static-web-server
