version: '3.8'

services:
  web:
    build:
      context: ./static-web-server # Chemin vers le dossier contenant votre Dockerfile
    ports:
      - "8080:80" # Mappe le port 80 du conteneur au port 8080 de votre machine
    container_name: static-web-server

  api:
    build:
      context: ./labo5-http-code-java
    ports:
      - "8081:8081"  # Redirige le port 8081 du conteneur vers le port 8081 de l'hôte
    container_name: todo-api
