# traefik.yaml

# Define entrypoints for HTTP and HTTPS
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

# Enable the Docker provider
providers:
  docker:
    exposedByDefault: false

# Define TLS settings using the self-signed certificate
tls:
  certificates:
        certFile: /etc/traefik/certificates/traefik.crt
        keyFile: /etc/traefik/certificates/traefik.key

# Configure the Traefik dashboard
api:
  dashboard: true
  insecure: true